### ISSUE TITLE
Add Template for Pull Request

### ISSUE THREAD

**Issue by jimenezz22** [ByteBuildersLabs/StarknetContracts#6]
The template must have the following parts:
- Title: Pull Request Overview
- Summary
- Changes Made
- Tests Results
- Next Steps

Use the following photo as an example:
<img width="833" alt="Screenshot 2024-10-29 at 11 36 24 AM" src="https://github.com/user-attachments/assets/b6c875ea-380d-4be9-9291-9ca3969b20ed">

**Comment by petersdt** [comment]
I’m interested in this one. if it is avaliable for contribution 
previous contribution :

- [cairo book](https://github.com/cairo-book/cairo-book/pull/788)

**Comment by Akshola00** [comment]
I'd like to take this issue.

**Comment by martinvibes** [comment]
Can I be assigned to this?

**Comment by CollinsC1O** [comment]
Can I take care of this issue?

**Comment by MPSxDev** [comment]
I would love to take on this issue. I am a member of the Dojo Coding. I am immediately available. @jimenezz22

**Comment by nov0ax** [comment]
Let me handle this issue!
I'd like to make my first contribution to this amazing project, I've been on an intesive road map with the help of Dojo Coding CR comunity

**Comment by derianrddev** [comment]
Hello, I’m Derian, a software engineer focused on full-stack web development, and I’m currently part of Dojo Coding. I’d like to work on this issue.

Here’s how I would solve the issue:

Create the .github folder in the root of the repository.
Add the template within that folder with the parts described in the issue.
Save and upload the file to the repository.
If I have any questions, I’ll ask in the Telegram group as soon as possible.
I’ll open a PR and wait for your feedback.
I’ll make the necessary changes according to the PR review.

**Comment by aguilar1x** [comment]
Could I be assigned to this?

**Comment by aguilar1x** [comment]
I am a software developer. I am also a member of Dojo Coding, where I am expanding my experience in Cairo and Web3 technologies. I am excited to learn and be a part of this project with my first contribution.

To address this issue, I would take the following steps:

1. Review the project PR: I will analyze the PR in detail to understand its structure, and functionality.

2. Create Repository: The folder with the repository will be created to work on it.

3. Analyze the proposed template in detail: it will be analyzed to better understand what is required in the issue.

4. Check the execution steps:

- Title, description of the “Pull Request” issue.
- ⁠Summary, reference to the issue that is being closed with this Pull Request.
- ⁠Changes Made, list of changes made, detailing the affected files or functionality.
- ⁠Text Results, details of any tests that failed or areas where improvement is needed.
- ⁠Next Steps, any pending actions will be taken after merging the Pull Request, if any, or updates if required.

5. File: The template described for making the PR will be uploaded

6. Final Review, a final review will be done so that the PR is perfect and also on time and in the correct manner.

7. Questions or help: If I run into any problems or questions, I’ll reach out to the maintainers for assistance.

**Comment by JosueBrenes** [comment]
Hi, I'm **Josué Brenes** and I'll be working on issue.
I'm Dojo Coding member.

I estimate this will take **1 day** to complete.

To resolve this, I would create a Markdown template file (pull_request_template.md) in the .github directory of the repository. This file would include the required sections in Markdown format, making it automatically available in each Pull Request.

```tsx

# Pull Request Overview

## 📝 Summary
- Closes #(issue)
- Brief description of the purpose of the Pull Request.

## 🔄 Changes Made
- List of code changes, specifying the modules or sections affected.

## 🧪 Tests Results
- Results of the tests executed.
  - Example: "Unit tests: 15/15 passed"
  - Example: "Integration tests: 10/10 passed"

## 🚀 Next Steps
- Pending actions or next steps if applicable (e.g., additional reviews or tests by other teams).
```

**Comment by aguilar1x** [comment]
I am a software developer. I am also a member of Dojo Coding, where I am expanding my experience in Cairo and Web3 technologies. I am excited to learn and be a part of this project with my first contribution.

To address this issue, I would take the following steps:

1. Review the project PR: I will analyze the PR in detail to understand its structure and functionality.

2. Create Repository and readme.md: The folder with the repository to work on and the readme.md to work on the template will be created.

3. Analyze the proposed template in detail: it will be analyzed to better understand what is required in the issue.

4. Check the execution steps:

- Title, description of the “Pull Request” issue.
- ⁠Summary, reference to the issue that is being closed with this Pull Request.
- ⁠Changes Made, list of changes made, detailing the affected files or functionalities.
- ⁠Text Results, details of any failed tests or areas that need improvement.
- ⁠Next Steps, any pending actions after merging the Pull Request, if any, or updates if required.

5. File: The template described for making the PR will be uploaded.

6. Final Review, a final review will be done to ensure that the PR is perfect and also on time.

7. Questions or help: If I run into any problems or questions, I’ll reach out to the maintainers for assistance.

**Comment by aguilar1x** [comment]
I am a software developer. I am also a member of Dojo Coding, where I am expanding my experience in Cairo and Web3 technologies. I am excited to learn and be a part of this project with my first contribution.

To address this issue, I would take the following steps:

1. Review the project PR: I will analyze the PR in detail to understand its structure and functionality.

2. Create Repository and readme.md: The folder with the repository to work on and the readme.md to work on the template will be created.

3. Analyze the proposed template in detail: it will be analyzed to better understand what is required in the issue.

4. Check the execution steps:

- Title, description of the “Pull Request” issue.
- ⁠Summary, reference to the issue that is being closed with this Pull Request.
- ⁠Changes Made, list of changes made, detailing the affected files or functionalities.
- ⁠Text Results, details of any failed tests or areas that need improvement.
- ⁠Next Steps, any pending actions after merging the Pull Request, if any, or updates if required.

5. File: The template described for making the PR will be uploaded.

6. Final Review, a final review will be done to ensure that the PR is perfect and also on time.

7. Questions or help: If I run into any problems or questions, I’ll reach out to the maintainers for assistance.

**Comment by akintewe** [comment]
I would love if i get assigned to this issue I’d like to help with this. I am very familiar with the documentation architecture. Thank you so much. ETA <6 hrs

**Comment by Kaminar-i** [comment]
Can I be assigned this as my first issue

**Comment by sigmadawg** [comment]
im a newbie contributor, i'd be grateful if you'd give me the opportunity to work in this.

**Comment by danielcdz** [comment]
@aguilar1x go ahead
